### PR TITLE
Multipage gui constructors

### PR DESCRIPTION
**Pull request by the-codeboy**

### CODE REVIEW

**Comment by dev-null-undefined** [comment]
Shouldn't we be merging this into the AdvancedAction branch instead of main so we don't get into some merge conflicts?

**Comment by the-codeboy** [comment]
Uh I didn't realize that I had duplicate commits

**Comment by the-codeboy** [comment]
Do you know how to fix that?

**Comment by dev-null-undefined** [comment]
Should be done

**Pull request merged**
